/**
 * 🏛️ RBAC Prisma Seed v8.3 - Phase 1 Generated
 * BeeSmart Pro Construction ERP
 *
 * Generated from: rbac.schema.v8.3.yml
 * Generated on: 2025-11-18T20:32:50.525Z
 *
 * PHASE 1 SEED DATA:
 * - 5 active internal roles
 * - 10 total roles
 * - 137 permissions
 * - Baseline permissions only
 */

import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

// ============================================================================
// ROLE SEED DATA
// ============================================================================

export const roleSeeds = [
  {
    code: 'ADMIN',
    name: 'Administrator',
    description: 'Tenant owner with full CRUD on all tenant data, no platform/system power',
    hierarchy: 0,
    roleType: 'INTERNAL',
    isActive: true,
    phase1Status: 'ACTIVE',
    businessContext: {
          "typical_users": [
                "Tenant Owners",
                "Company Owners",
                "Business Administrators"
          ],
          "access_scope": "All tenant business data and configuration",
          "use_cases": [
                "Tenant management",
                "User administration",
                "Full business operations"
          ],
          "financial_scope": "Complete tenant financial visibility and control"
    },
  },
  {
    code: 'PROJECT_MANAGER',
    name: 'Project Manager',
    description: 'Broad but scoped access to own/assigned projects, critical actions gated by TenantSettings',
    hierarchy: 2,
    roleType: 'INTERNAL',
    isActive: true,
    phase1Status: 'ACTIVE',
    businessContext: {
          "typical_users": [
                "Project Managers",
                "Construction Managers",
                "Site Supervisors"
          ],
          "access_scope": "Own/assigned projects, estimates, invoices, tasks",
          "use_cases": [
                "Project execution",
                "Team coordination",
                "Client communication"
          ],
          "financial_scope": "Project-level financial visibility, no tenant-wide profit/KPIs",
          "critical_note": "Approval and financial insight permissions gated by TenantSettings"
    },
  },
  {
    code: 'WORKER',
    name: 'Worker',
    description: 'Execution role for tasks, own time/expenses, assigned project visibility only',
    hierarchy: 8,
    roleType: 'INTERNAL',
    isActive: true,
    phase1Status: 'ACTIVE',
    businessContext: {
          "typical_users": [
                "Field Workers",
                "Technicians",
                "Office Staff",
                "Contractors"
          ],
          "access_scope": "Assigned tasks, own time/expenses, assigned project operational details",
          "use_cases": [
                "Task execution",
                "Time tracking",
                "Progress reporting",
                "Expense submission"
          ],
          "financial_scope": "No financial data access"
    },
  },
  {
    code: 'DRIVER',
    name: 'Driver',
    description: 'Delivery/logistics role with minimal project info and delivery task focus',
    hierarchy: 9,
    roleType: 'INTERNAL',
    isActive: true,
    phase1Status: 'ACTIVE',
    businessContext: {
          "typical_users": [
                "Delivery Drivers",
                "Logistics Staff",
                "Couriers",
                "Delivery Personnel"
          ],
          "access_scope": "Delivery tasks, delivery project info, own time/expenses, delivery docs",
          "use_cases": [
                "Delivery execution",
                "Basic time logging",
                "Delivery documentation"
          ],
          "financial_scope": "No financial data access"
    },
  },
  {
    code: 'VIEWER',
    name: 'Viewer',
    description: 'Read-only sandbox-only role for demo/training, NEVER for production tenants',
    hierarchy: 10,
    roleType: 'INTERNAL',
    isActive: true,
    phase1Status: 'ACTIVE',
    businessContext: {
          "typical_users": [
                "Demo Users",
                "Trainees",
                "Prospects",
                "Evaluators"
          ],
          "access_scope": "Read-only access in sandbox tenants ONLY",
          "use_cases": [
                "Product demonstration",
                "Training",
                "System evaluation"
          ],
          "financial_scope": "Demo financial data only (sandbox environment)",
          "enforcement_critical": "MUST be enforced via RLS - no production tenant access allowed"
    },
  },
  {
    code: 'CLIENT_OWNER',
    name: 'Client Owner',
    description: 'Client company owner with project oversight',
    hierarchy: 6,
    roleType: 'EXTERNAL',
    isActive: false,
    phase1Status: 'PRESERVED',
    businessContext: {},
  },
  {
    code: 'CLIENT_MANAGER',
    name: 'Client Manager',
    description: 'Client project management and coordination',
    hierarchy: 7,
    roleType: 'EXTERNAL',
    isActive: false,
    phase1Status: 'PRESERVED',
    businessContext: {},
  },
  {
    code: 'CLIENT_VIEWER',
    name: 'Client Viewer',
    description: 'Client stakeholder with limited access',
    hierarchy: 8,
    roleType: 'EXTERNAL',
    isActive: false,
    phase1Status: 'PRESERVED',
    businessContext: {},
  },
  {
    code: 'VENDOR',
    name: 'Vendor/Supplier',
    description: 'External vendor or supplier access',
    hierarchy: 7,
    roleType: 'EXTERNAL',
    isActive: false,
    phase1Status: 'PRESERVED',
    businessContext: {},
  },
  {
    code: 'GUEST',
    name: 'Guest User',
    description: 'Temporary or demo access',
    hierarchy: 10,
    roleType: 'EXTERNAL',
    isActive: false,
    phase1Status: 'PRESERVED',
    businessContext: {},
  },
];

// ============================================================================
// PERMISSION SEED DATA
// ============================================================================

export const permissionSeeds = [
  {
    code: 'tenant:read',
    domain: 'tenant',
    action: 'read',
    subaction: null,
    description: 'read tenant',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'tenant:update',
    domain: 'tenant',
    action: 'update',
    subaction: null,
    description: 'update tenant',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'tenant:manage:modules',
    domain: 'tenant',
    action: 'manage',
    subaction: 'modules',
    description: 'manage tenant (modules)',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'tenant:manage:features',
    domain: 'tenant',
    action: 'manage',
    subaction: 'features',
    description: 'manage tenant (features)',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'identity:invite:user',
    domain: 'identity',
    action: 'invite',
    subaction: 'user',
    description: 'invite identity (user)',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'identity:read:tenant_users',
    domain: 'identity',
    action: 'read',
    subaction: 'tenant_users',
    description: 'read identity (tenant_users)',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'identity:update:tenant_users',
    domain: 'identity',
    action: 'update',
    subaction: 'tenant_users',
    description: 'update identity (tenant_users)',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'identity:read:own',
    domain: 'identity',
    action: 'read',
    subaction: 'own',
    description: 'read identity (own)',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'identity:update:own',
    domain: 'identity',
    action: 'update',
    subaction: 'own',
    description: 'update identity (own)',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'membership:manage:roles',
    domain: 'membership',
    action: 'manage',
    subaction: 'roles',
    description: 'manage membership (roles)',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'membership:read:tenant_members',
    domain: 'membership',
    action: 'read',
    subaction: 'tenant_members',
    description: 'read membership (tenant_members)',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'membership:update:tenant_members',
    domain: 'membership',
    action: 'update',
    subaction: 'tenant_members',
    description: 'update membership (tenant_members)',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'accesscontrol:read',
    domain: 'accesscontrol',
    action: 'read',
    subaction: null,
    description: 'read accesscontrol',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'accesscontrol:update:tenant_roles',
    domain: 'accesscontrol',
    action: 'update',
    subaction: 'tenant_roles',
    description: 'update accesscontrol (tenant_roles)',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'accesscontrol:manage:service_accounts',
    domain: 'accesscontrol',
    action: 'manage',
    subaction: 'service_accounts',
    description: 'manage accesscontrol (service_accounts)',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'estimate:create',
    domain: 'estimate',
    action: 'create',
    subaction: null,
    description: 'create estimate',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'estimate:list',
    domain: 'estimate',
    action: 'list',
    subaction: null,
    description: 'list estimate',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'estimate:read',
    domain: 'estimate',
    action: 'read',
    subaction: null,
    description: 'read estimate',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'estimate:update',
    domain: 'estimate',
    action: 'update',
    subaction: null,
    description: 'update estimate',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'estimate:send',
    domain: 'estimate',
    action: 'send',
    subaction: null,
    description: 'send estimate',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'estimate:list:own',
    domain: 'estimate',
    action: 'list',
    subaction: 'own',
    description: 'list estimate (own)',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'estimate:read:own',
    domain: 'estimate',
    action: 'read',
    subaction: 'own',
    description: 'read estimate (own)',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'estimate:update:own',
    domain: 'estimate',
    action: 'update',
    subaction: 'own',
    description: 'update estimate (own)',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'estimate:send:own',
    domain: 'estimate',
    action: 'send',
    subaction: 'own',
    description: 'send estimate (own)',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'estimate:delete',
    domain: 'estimate',
    action: 'delete',
    subaction: null,
    description: 'delete estimate',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'estimate:approve',
    domain: 'estimate',
    action: 'approve',
    subaction: null,
    description: 'approve estimate',
    isBaseline: false,
    isCritical: true,
  },
  {
    code: 'estimate:delete:own',
    domain: 'estimate',
    action: 'delete',
    subaction: 'own',
    description: 'delete estimate (own)',
    isBaseline: false,
    isCritical: true,
  },
  {
    code: 'estimate:read:profit',
    domain: 'estimate',
    action: 'read',
    subaction: 'profit',
    description: 'read estimate (profit)',
    isBaseline: false,
    isCritical: true,
  },
  {
    code: 'invoice:create',
    domain: 'invoice',
    action: 'create',
    subaction: null,
    description: 'create invoice',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'invoice:list',
    domain: 'invoice',
    action: 'list',
    subaction: null,
    description: 'list invoice',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'invoice:read',
    domain: 'invoice',
    action: 'read',
    subaction: null,
    description: 'read invoice',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'invoice:update',
    domain: 'invoice',
    action: 'update',
    subaction: null,
    description: 'update invoice',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'invoice:send',
    domain: 'invoice',
    action: 'send',
    subaction: null,
    description: 'send invoice',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'invoice:list:own',
    domain: 'invoice',
    action: 'list',
    subaction: 'own',
    description: 'list invoice (own)',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'invoice:read:own',
    domain: 'invoice',
    action: 'read',
    subaction: 'own',
    description: 'read invoice (own)',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'invoice:update:own',
    domain: 'invoice',
    action: 'update',
    subaction: 'own',
    description: 'update invoice (own)',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'invoice:send:own',
    domain: 'invoice',
    action: 'send',
    subaction: 'own',
    description: 'send invoice (own)',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'invoice:delete',
    domain: 'invoice',
    action: 'delete',
    subaction: null,
    description: 'delete invoice',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'invoice:approve',
    domain: 'invoice',
    action: 'approve',
    subaction: null,
    description: 'approve invoice',
    isBaseline: false,
    isCritical: true,
  },
  {
    code: 'invoice:writeoff',
    domain: 'invoice',
    action: 'writeoff',
    subaction: null,
    description: 'writeoff invoice',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'invoice:delete:own',
    domain: 'invoice',
    action: 'delete',
    subaction: 'own',
    description: 'delete invoice (own)',
    isBaseline: false,
    isCritical: true,
  },
  {
    code: 'invoice:read:profit',
    domain: 'invoice',
    action: 'read',
    subaction: 'profit',
    description: 'read invoice (profit)',
    isBaseline: false,
    isCritical: true,
  },
  {
    code: 'project:create',
    domain: 'project',
    action: 'create',
    subaction: null,
    description: 'create project',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'project:list',
    domain: 'project',
    action: 'list',
    subaction: null,
    description: 'list project',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'project:read',
    domain: 'project',
    action: 'read',
    subaction: null,
    description: 'read project',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'project:update',
    domain: 'project',
    action: 'update',
    subaction: null,
    description: 'update project',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'project:assign:pm',
    domain: 'project',
    action: 'assign',
    subaction: 'pm',
    description: 'assign project (pm)',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'project:assign:worker',
    domain: 'project',
    action: 'assign',
    subaction: 'worker',
    description: 'assign project (worker)',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'project:assign:driver',
    domain: 'project',
    action: 'assign',
    subaction: 'driver',
    description: 'assign project (driver)',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'project:create:own',
    domain: 'project',
    action: 'create',
    subaction: 'own',
    description: 'create project (own)',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'project:list:own',
    domain: 'project',
    action: 'list',
    subaction: 'own',
    description: 'list project (own)',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'project:read:own',
    domain: 'project',
    action: 'read',
    subaction: 'own',
    description: 'read project (own)',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'project:update:own',
    domain: 'project',
    action: 'update',
    subaction: 'own',
    description: 'update project (own)',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'project:read:team',
    domain: 'project',
    action: 'read',
    subaction: 'team',
    description: 'read project (team)',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'project:read:schedule',
    domain: 'project',
    action: 'read',
    subaction: 'schedule',
    description: 'read project (schedule)',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'project:list:assigned',
    domain: 'project',
    action: 'list',
    subaction: 'assigned',
    description: 'list project (assigned)',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'project:read:assigned',
    domain: 'project',
    action: 'read',
    subaction: 'assigned',
    description: 'read project (assigned)',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'project:list:delivery_assigned',
    domain: 'project',
    action: 'list',
    subaction: 'delivery_assigned',
    description: 'list project (delivery_assigned)',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'project:read:delivery_info',
    domain: 'project',
    action: 'read',
    subaction: 'delivery_info',
    description: 'read project (delivery_info)',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'project:delete',
    domain: 'project',
    action: 'delete',
    subaction: null,
    description: 'delete project',
    isBaseline: false,
    isCritical: true,
  },
  {
    code: 'project:read:financial',
    domain: 'project',
    action: 'read',
    subaction: 'financial',
    description: 'read project (financial)',
    isBaseline: false,
    isCritical: true,
  },
  {
    code: 'task:create',
    domain: 'task',
    action: 'create',
    subaction: null,
    description: 'create task',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'task:list',
    domain: 'task',
    action: 'list',
    subaction: null,
    description: 'list task',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'task:read',
    domain: 'task',
    action: 'read',
    subaction: null,
    description: 'read task',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'task:update',
    domain: 'task',
    action: 'update',
    subaction: null,
    description: 'update task',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'task:delete',
    domain: 'task',
    action: 'delete',
    subaction: null,
    description: 'delete task',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'task:assign:worker',
    domain: 'task',
    action: 'assign',
    subaction: 'worker',
    description: 'assign task (worker)',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'task:assign:driver',
    domain: 'task',
    action: 'assign',
    subaction: 'driver',
    description: 'assign task (driver)',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'task:create:project',
    domain: 'task',
    action: 'create',
    subaction: 'project',
    description: 'create task (project)',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'task:list:project',
    domain: 'task',
    action: 'list',
    subaction: 'project',
    description: 'list task (project)',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'task:read:project',
    domain: 'task',
    action: 'read',
    subaction: 'project',
    description: 'read task (project)',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'task:update:project',
    domain: 'task',
    action: 'update',
    subaction: 'project',
    description: 'update task (project)',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'task:list:assigned',
    domain: 'task',
    action: 'list',
    subaction: 'assigned',
    description: 'list task (assigned)',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'task:read:assigned',
    domain: 'task',
    action: 'read',
    subaction: 'assigned',
    description: 'read task (assigned)',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'task:update:own',
    domain: 'task',
    action: 'update',
    subaction: 'own',
    description: 'update task (own)',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'task:list:delivery',
    domain: 'task',
    action: 'list',
    subaction: 'delivery',
    description: 'list task (delivery)',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'task:read:delivery',
    domain: 'task',
    action: 'read',
    subaction: 'delivery',
    description: 'read task (delivery)',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'task:update:delivery',
    domain: 'task',
    action: 'update',
    subaction: 'delivery',
    description: 'update task (delivery)',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'expenses:create',
    domain: 'expenses',
    action: 'create',
    subaction: null,
    description: 'create expenses',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'expenses:list',
    domain: 'expenses',
    action: 'list',
    subaction: null,
    description: 'list expenses',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'expenses:read',
    domain: 'expenses',
    action: 'read',
    subaction: null,
    description: 'read expenses',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'expenses:update',
    domain: 'expenses',
    action: 'update',
    subaction: null,
    description: 'update expenses',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'expenses:delete',
    domain: 'expenses',
    action: 'delete',
    subaction: null,
    description: 'delete expenses',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'expenses:approve',
    domain: 'expenses',
    action: 'approve',
    subaction: null,
    description: 'approve expenses',
    isBaseline: false,
    isCritical: true,
  },
  {
    code: 'expenses:list:project',
    domain: 'expenses',
    action: 'list',
    subaction: 'project',
    description: 'list expenses (project)',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'expenses:read:project',
    domain: 'expenses',
    action: 'read',
    subaction: 'project',
    description: 'read expenses (project)',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'expenses:create:own',
    domain: 'expenses',
    action: 'create',
    subaction: 'own',
    description: 'create expenses (own)',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'expenses:list:own',
    domain: 'expenses',
    action: 'list',
    subaction: 'own',
    description: 'list expenses (own)',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'expenses:read:own',
    domain: 'expenses',
    action: 'read',
    subaction: 'own',
    description: 'read expenses (own)',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'expenses:create:delivery',
    domain: 'expenses',
    action: 'create',
    subaction: 'delivery',
    description: 'create expenses (delivery)',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'time:read:tenant',
    domain: 'time',
    action: 'read',
    subaction: 'tenant',
    description: 'read time (tenant)',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'time:correct:tenant',
    domain: 'time',
    action: 'correct',
    subaction: 'tenant',
    description: 'correct time (tenant)',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'time:read:own',
    domain: 'time',
    action: 'read',
    subaction: 'own',
    description: 'read time (own)',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'time:create:own_entry',
    domain: 'time',
    action: 'create',
    subaction: 'own_entry',
    description: 'create time (own_entry)',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'scheduling:create',
    domain: 'scheduling',
    action: 'create',
    subaction: null,
    description: 'create scheduling',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'scheduling:read',
    domain: 'scheduling',
    action: 'read',
    subaction: null,
    description: 'read scheduling',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'scheduling:update',
    domain: 'scheduling',
    action: 'update',
    subaction: null,
    description: 'update scheduling',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'scheduling:read:own',
    domain: 'scheduling',
    action: 'read',
    subaction: 'own',
    description: 'read scheduling (own)',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'payroll:read:tenant',
    domain: 'payroll',
    action: 'read',
    subaction: 'tenant',
    description: 'read payroll (tenant)',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'payroll:run',
    domain: 'payroll',
    action: 'run',
    subaction: null,
    description: 'run payroll',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'payroll:update',
    domain: 'payroll',
    action: 'update',
    subaction: null,
    description: 'update payroll',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'payroll:read:own',
    domain: 'payroll',
    action: 'read',
    subaction: 'own',
    description: 'read payroll (own)',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'inventory:create:item',
    domain: 'inventory',
    action: 'create',
    subaction: 'item',
    description: 'create inventory (item)',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'inventory:list',
    domain: 'inventory',
    action: 'list',
    subaction: null,
    description: 'list inventory',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'inventory:read',
    domain: 'inventory',
    action: 'read',
    subaction: null,
    description: 'read inventory',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'inventory:update:item',
    domain: 'inventory',
    action: 'update',
    subaction: 'item',
    description: 'update inventory (item)',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'inventory:adjust:quantity',
    domain: 'inventory',
    action: 'adjust',
    subaction: 'quantity',
    description: 'adjust inventory (quantity)',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'inventory:investigate:loss',
    domain: 'inventory',
    action: 'investigate',
    subaction: 'loss',
    description: 'investigate inventory (loss)',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'inventory:read:delivery_items',
    domain: 'inventory',
    action: 'read',
    subaction: 'delivery_items',
    description: 'read inventory (delivery_items)',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'crm:create',
    domain: 'crm',
    action: 'create',
    subaction: null,
    description: 'create crm',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'crm:list',
    domain: 'crm',
    action: 'list',
    subaction: null,
    description: 'list crm',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'crm:read',
    domain: 'crm',
    action: 'read',
    subaction: null,
    description: 'read crm',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'crm:update',
    domain: 'crm',
    action: 'update',
    subaction: null,
    description: 'update crm',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'crm:delete',
    domain: 'crm',
    action: 'delete',
    subaction: null,
    description: 'delete crm',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'documents:create',
    domain: 'documents',
    action: 'create',
    subaction: null,
    description: 'create documents',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'documents:list',
    domain: 'documents',
    action: 'list',
    subaction: null,
    description: 'list documents',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'documents:read',
    domain: 'documents',
    action: 'read',
    subaction: null,
    description: 'read documents',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'documents:update',
    domain: 'documents',
    action: 'update',
    subaction: null,
    description: 'update documents',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'documents:delete',
    domain: 'documents',
    action: 'delete',
    subaction: null,
    description: 'delete documents',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'documents:list:project',
    domain: 'documents',
    action: 'list',
    subaction: 'project',
    description: 'list documents (project)',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'documents:read:project',
    domain: 'documents',
    action: 'read',
    subaction: 'project',
    description: 'read documents (project)',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'documents:upload:project',
    domain: 'documents',
    action: 'upload',
    subaction: 'project',
    description: 'upload documents (project)',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'documents:comment:project',
    domain: 'documents',
    action: 'comment',
    subaction: 'project',
    description: 'comment documents (project)',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'documents:list:assigned',
    domain: 'documents',
    action: 'list',
    subaction: 'assigned',
    description: 'list documents (assigned)',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'documents:read:assigned',
    domain: 'documents',
    action: 'read',
    subaction: 'assigned',
    description: 'read documents (assigned)',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'documents:upload:assigned',
    domain: 'documents',
    action: 'upload',
    subaction: 'assigned',
    description: 'upload documents (assigned)',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'documents:upload:delivery',
    domain: 'documents',
    action: 'upload',
    subaction: 'delivery',
    description: 'upload documents (delivery)',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'documents:read:delivery',
    domain: 'documents',
    action: 'read',
    subaction: 'delivery',
    description: 'read documents (delivery)',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'ai:ask',
    domain: 'ai',
    action: 'ask',
    subaction: null,
    description: 'ask ai',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'ai:assist:tenant',
    domain: 'ai',
    action: 'assist',
    subaction: 'tenant',
    description: 'assist ai (tenant)',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'ai:generate:financial_report',
    domain: 'ai',
    action: 'generate',
    subaction: 'financial_report',
    description: 'generate ai (financial_report)',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'ai:generate:project_report',
    domain: 'ai',
    action: 'generate',
    subaction: 'project_report',
    description: 'generate ai (project_report)',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'ai:assist:project',
    domain: 'ai',
    action: 'assist',
    subaction: 'project',
    description: 'assist ai (project)',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'ai:assist:task',
    domain: 'ai',
    action: 'assist',
    subaction: 'task',
    description: 'assist ai (task)',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'ai:assist:delivery',
    domain: 'ai',
    action: 'assist',
    subaction: 'delivery',
    description: 'assist ai (delivery)',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'ai:generate:demo_report',
    domain: 'ai',
    action: 'generate',
    subaction: 'demo_report',
    description: 'generate ai (demo_report)',
    isBaseline: true,
    isCritical: false,
  },
  {
    code: 'analytics:read:tenant_kpis',
    domain: 'analytics',
    action: 'read',
    subaction: 'tenant_kpis',
    description: 'read analytics (tenant_kpis)',
    isBaseline: false,
    isCritical: true,
  },
];

// ============================================================================
// ROLE PERMISSION GRANTS (Baseline Only)
// ============================================================================

export const rolePermissionSeeds = [
  { roleCode: 'ADMIN', permissionCode: 'tenant:read', isBaseline: true },
  { roleCode: 'ADMIN', permissionCode: 'tenant:update', isBaseline: true },
  { roleCode: 'ADMIN', permissionCode: 'tenant:manage:modules', isBaseline: true },
  { roleCode: 'ADMIN', permissionCode: 'tenant:manage:features', isBaseline: true },
  { roleCode: 'ADMIN', permissionCode: 'identity:invite:user', isBaseline: true },
  { roleCode: 'ADMIN', permissionCode: 'identity:read:tenant_users', isBaseline: true },
  { roleCode: 'ADMIN', permissionCode: 'identity:update:tenant_users', isBaseline: true },
  { roleCode: 'ADMIN', permissionCode: 'identity:read:own', isBaseline: true },
  { roleCode: 'ADMIN', permissionCode: 'identity:update:own', isBaseline: true },
  { roleCode: 'ADMIN', permissionCode: 'membership:manage:roles', isBaseline: true },
  { roleCode: 'ADMIN', permissionCode: 'membership:read:tenant_members', isBaseline: true },
  { roleCode: 'ADMIN', permissionCode: 'membership:update:tenant_members', isBaseline: true },
  { roleCode: 'ADMIN', permissionCode: 'accesscontrol:read', isBaseline: true },
  { roleCode: 'ADMIN', permissionCode: 'accesscontrol:update:tenant_roles', isBaseline: true },
  { roleCode: 'ADMIN', permissionCode: 'accesscontrol:manage:service_accounts', isBaseline: true },
  { roleCode: 'ADMIN', permissionCode: 'estimate:create', isBaseline: true },
  { roleCode: 'ADMIN', permissionCode: 'estimate:list', isBaseline: true },
  { roleCode: 'ADMIN', permissionCode: 'estimate:read', isBaseline: true },
  { roleCode: 'ADMIN', permissionCode: 'estimate:update', isBaseline: true },
  { roleCode: 'ADMIN', permissionCode: 'estimate:delete', isBaseline: true },
  { roleCode: 'ADMIN', permissionCode: 'estimate:send', isBaseline: true },
  { roleCode: 'ADMIN', permissionCode: 'estimate:approve', isBaseline: true },
  { roleCode: 'ADMIN', permissionCode: 'estimate:list:own', isBaseline: true },
  { roleCode: 'ADMIN', permissionCode: 'estimate:read:own', isBaseline: true },
  { roleCode: 'ADMIN', permissionCode: 'estimate:update:own', isBaseline: true },
  { roleCode: 'ADMIN', permissionCode: 'estimate:send:own', isBaseline: true },
  { roleCode: 'ADMIN', permissionCode: 'estimate:delete:own', isBaseline: true },
  { roleCode: 'ADMIN', permissionCode: 'estimate:read:profit', isBaseline: true },
  { roleCode: 'ADMIN', permissionCode: 'invoice:create', isBaseline: true },
  { roleCode: 'ADMIN', permissionCode: 'invoice:list', isBaseline: true },
  { roleCode: 'ADMIN', permissionCode: 'invoice:read', isBaseline: true },
  { roleCode: 'ADMIN', permissionCode: 'invoice:update', isBaseline: true },
  { roleCode: 'ADMIN', permissionCode: 'invoice:delete', isBaseline: true },
  { roleCode: 'ADMIN', permissionCode: 'invoice:send', isBaseline: true },
  { roleCode: 'ADMIN', permissionCode: 'invoice:approve', isBaseline: true },
  { roleCode: 'ADMIN', permissionCode: 'invoice:writeoff', isBaseline: true },
  { roleCode: 'ADMIN', permissionCode: 'invoice:list:own', isBaseline: true },
  { roleCode: 'ADMIN', permissionCode: 'invoice:read:own', isBaseline: true },
  { roleCode: 'ADMIN', permissionCode: 'invoice:update:own', isBaseline: true },
  { roleCode: 'ADMIN', permissionCode: 'invoice:send:own', isBaseline: true },
  { roleCode: 'ADMIN', permissionCode: 'invoice:delete:own', isBaseline: true },
  { roleCode: 'ADMIN', permissionCode: 'invoice:read:profit', isBaseline: true },
  { roleCode: 'ADMIN', permissionCode: 'project:create', isBaseline: true },
  { roleCode: 'ADMIN', permissionCode: 'project:list', isBaseline: true },
  { roleCode: 'ADMIN', permissionCode: 'project:read', isBaseline: true },
  { roleCode: 'ADMIN', permissionCode: 'project:update', isBaseline: true },
  { roleCode: 'ADMIN', permissionCode: 'project:delete', isBaseline: true },
  { roleCode: 'ADMIN', permissionCode: 'project:assign:pm', isBaseline: true },
  { roleCode: 'ADMIN', permissionCode: 'project:assign:worker', isBaseline: true },
  { roleCode: 'ADMIN', permissionCode: 'project:assign:driver', isBaseline: true },
  { roleCode: 'ADMIN', permissionCode: 'project:read:financial', isBaseline: true },
  { roleCode: 'ADMIN', permissionCode: 'project:create:own', isBaseline: true },
  { roleCode: 'ADMIN', permissionCode: 'project:list:own', isBaseline: true },
  { roleCode: 'ADMIN', permissionCode: 'project:read:own', isBaseline: true },
  { roleCode: 'ADMIN', permissionCode: 'project:update:own', isBaseline: true },
  { roleCode: 'ADMIN', permissionCode: 'project:read:team', isBaseline: true },
  { roleCode: 'ADMIN', permissionCode: 'project:read:schedule', isBaseline: true },
  { roleCode: 'ADMIN', permissionCode: 'task:create', isBaseline: true },
  { roleCode: 'ADMIN', permissionCode: 'task:list', isBaseline: true },
  { roleCode: 'ADMIN', permissionCode: 'task:read', isBaseline: true },
  { roleCode: 'ADMIN', permissionCode: 'task:update', isBaseline: true },
  { roleCode: 'ADMIN', permissionCode: 'task:delete', isBaseline: true },
  { roleCode: 'ADMIN', permissionCode: 'task:assign:worker', isBaseline: true },
  { roleCode: 'ADMIN', permissionCode: 'task:assign:driver', isBaseline: true },
  { roleCode: 'ADMIN', permissionCode: 'task:create:project', isBaseline: true },
  { roleCode: 'ADMIN', permissionCode: 'task:list:project', isBaseline: true },
  { roleCode: 'ADMIN', permissionCode: 'task:read:project', isBaseline: true },
  { roleCode: 'ADMIN', permissionCode: 'task:update:project', isBaseline: true },
  { roleCode: 'ADMIN', permissionCode: 'expenses:create', isBaseline: true },
  { roleCode: 'ADMIN', permissionCode: 'expenses:list', isBaseline: true },
  { roleCode: 'ADMIN', permissionCode: 'expenses:read', isBaseline: true },
  { roleCode: 'ADMIN', permissionCode: 'expenses:update', isBaseline: true },
  { roleCode: 'ADMIN', permissionCode: 'expenses:delete', isBaseline: true },
  { roleCode: 'ADMIN', permissionCode: 'expenses:approve', isBaseline: true },
  { roleCode: 'ADMIN', permissionCode: 'expenses:list:project', isBaseline: true },
  { roleCode: 'ADMIN', permissionCode: 'expenses:read:project', isBaseline: true },
  { roleCode: 'ADMIN', permissionCode: 'time:read:tenant', isBaseline: true },
  { roleCode: 'ADMIN', permissionCode: 'time:correct:tenant', isBaseline: true },
  { roleCode: 'ADMIN', permissionCode: 'time:read:own', isBaseline: true },
  { roleCode: 'ADMIN', permissionCode: 'time:create:own_entry', isBaseline: true },
  { roleCode: 'ADMIN', permissionCode: 'scheduling:create', isBaseline: true },
  { roleCode: 'ADMIN', permissionCode: 'scheduling:read', isBaseline: true },
  { roleCode: 'ADMIN', permissionCode: 'scheduling:update', isBaseline: true },
  { roleCode: 'ADMIN', permissionCode: 'scheduling:read:own', isBaseline: true },
  { roleCode: 'ADMIN', permissionCode: 'payroll:read:tenant', isBaseline: true },
  { roleCode: 'ADMIN', permissionCode: 'payroll:run', isBaseline: true },
  { roleCode: 'ADMIN', permissionCode: 'payroll:update', isBaseline: true },
  { roleCode: 'ADMIN', permissionCode: 'payroll:read:own', isBaseline: true },
  { roleCode: 'ADMIN', permissionCode: 'inventory:create:item', isBaseline: true },
  { roleCode: 'ADMIN', permissionCode: 'inventory:list', isBaseline: true },
  { roleCode: 'ADMIN', permissionCode: 'inventory:read', isBaseline: true },
  { roleCode: 'ADMIN', permissionCode: 'inventory:update:item', isBaseline: true },
  { roleCode: 'ADMIN', permissionCode: 'inventory:adjust:quantity', isBaseline: true },
  { roleCode: 'ADMIN', permissionCode: 'inventory:investigate:loss', isBaseline: true },
  { roleCode: 'ADMIN', permissionCode: 'crm:create', isBaseline: true },
  { roleCode: 'ADMIN', permissionCode: 'crm:list', isBaseline: true },
  { roleCode: 'ADMIN', permissionCode: 'crm:read', isBaseline: true },
  { roleCode: 'ADMIN', permissionCode: 'crm:update', isBaseline: true },
  { roleCode: 'ADMIN', permissionCode: 'crm:delete', isBaseline: true },
  { roleCode: 'ADMIN', permissionCode: 'documents:create', isBaseline: true },
  { roleCode: 'ADMIN', permissionCode: 'documents:list', isBaseline: true },
  { roleCode: 'ADMIN', permissionCode: 'documents:read', isBaseline: true },
  { roleCode: 'ADMIN', permissionCode: 'documents:update', isBaseline: true },
  { roleCode: 'ADMIN', permissionCode: 'documents:delete', isBaseline: true },
  { roleCode: 'ADMIN', permissionCode: 'documents:list:project', isBaseline: true },
  { roleCode: 'ADMIN', permissionCode: 'documents:read:project', isBaseline: true },
  { roleCode: 'ADMIN', permissionCode: 'documents:upload:project', isBaseline: true },
  { roleCode: 'ADMIN', permissionCode: 'documents:comment:project', isBaseline: true },
  { roleCode: 'ADMIN', permissionCode: 'ai:ask', isBaseline: true },
  { roleCode: 'ADMIN', permissionCode: 'ai:assist:tenant', isBaseline: true },
  { roleCode: 'ADMIN', permissionCode: 'ai:generate:financial_report', isBaseline: true },
  { roleCode: 'ADMIN', permissionCode: 'ai:generate:project_report', isBaseline: true },
  { roleCode: 'ADMIN', permissionCode: 'ai:assist:project', isBaseline: true },
  { roleCode: 'ADMIN', permissionCode: 'analytics:read:tenant_kpis', isBaseline: true },
  { roleCode: 'PROJECT_MANAGER', permissionCode: 'identity:read:own', isBaseline: true },
  { roleCode: 'PROJECT_MANAGER', permissionCode: 'identity:update:own', isBaseline: true },
  { roleCode: 'PROJECT_MANAGER', permissionCode: 'estimate:create', isBaseline: true },
  { roleCode: 'PROJECT_MANAGER', permissionCode: 'estimate:list:own', isBaseline: true },
  { roleCode: 'PROJECT_MANAGER', permissionCode: 'estimate:read:own', isBaseline: true },
  { roleCode: 'PROJECT_MANAGER', permissionCode: 'estimate:update:own', isBaseline: true },
  { roleCode: 'PROJECT_MANAGER', permissionCode: 'estimate:send:own', isBaseline: true },
  { roleCode: 'PROJECT_MANAGER', permissionCode: 'invoice:create', isBaseline: true },
  { roleCode: 'PROJECT_MANAGER', permissionCode: 'invoice:list:own', isBaseline: true },
  { roleCode: 'PROJECT_MANAGER', permissionCode: 'invoice:read:own', isBaseline: true },
  { roleCode: 'PROJECT_MANAGER', permissionCode: 'invoice:update:own', isBaseline: true },
  { roleCode: 'PROJECT_MANAGER', permissionCode: 'invoice:send:own', isBaseline: true },
  { roleCode: 'PROJECT_MANAGER', permissionCode: 'project:create:own', isBaseline: true },
  { roleCode: 'PROJECT_MANAGER', permissionCode: 'project:list:own', isBaseline: true },
  { roleCode: 'PROJECT_MANAGER', permissionCode: 'project:read:own', isBaseline: true },
  { roleCode: 'PROJECT_MANAGER', permissionCode: 'project:update:own', isBaseline: true },
  { roleCode: 'PROJECT_MANAGER', permissionCode: 'project:assign:worker', isBaseline: true },
  { roleCode: 'PROJECT_MANAGER', permissionCode: 'project:assign:driver', isBaseline: true },
  { roleCode: 'PROJECT_MANAGER', permissionCode: 'project:read:team', isBaseline: true },
  { roleCode: 'PROJECT_MANAGER', permissionCode: 'project:read:schedule', isBaseline: true },
  { roleCode: 'PROJECT_MANAGER', permissionCode: 'task:create:project', isBaseline: true },
  { roleCode: 'PROJECT_MANAGER', permissionCode: 'task:list:project', isBaseline: true },
  { roleCode: 'PROJECT_MANAGER', permissionCode: 'task:read:project', isBaseline: true },
  { roleCode: 'PROJECT_MANAGER', permissionCode: 'task:update:project', isBaseline: true },
  { roleCode: 'PROJECT_MANAGER', permissionCode: 'task:assign:worker', isBaseline: true },
  { roleCode: 'PROJECT_MANAGER', permissionCode: 'task:assign:driver', isBaseline: true },
  { roleCode: 'PROJECT_MANAGER', permissionCode: 'expenses:list:project', isBaseline: true },
  { roleCode: 'PROJECT_MANAGER', permissionCode: 'expenses:read:project', isBaseline: true },
  { roleCode: 'PROJECT_MANAGER', permissionCode: 'time:read:own', isBaseline: true },
  { roleCode: 'PROJECT_MANAGER', permissionCode: 'time:create:own_entry', isBaseline: true },
  { roleCode: 'PROJECT_MANAGER', permissionCode: 'payroll:read:own', isBaseline: true },
  { roleCode: 'PROJECT_MANAGER', permissionCode: 'scheduling:read:own', isBaseline: true },
  { roleCode: 'PROJECT_MANAGER', permissionCode: 'documents:list:project', isBaseline: true },
  { roleCode: 'PROJECT_MANAGER', permissionCode: 'documents:read:project', isBaseline: true },
  { roleCode: 'PROJECT_MANAGER', permissionCode: 'documents:upload:project', isBaseline: true },
  { roleCode: 'PROJECT_MANAGER', permissionCode: 'documents:comment:project', isBaseline: true },
  { roleCode: 'PROJECT_MANAGER', permissionCode: 'ai:ask', isBaseline: true },
  { roleCode: 'PROJECT_MANAGER', permissionCode: 'ai:assist:project', isBaseline: true },
  { roleCode: 'PROJECT_MANAGER', permissionCode: 'ai:generate:project_report', isBaseline: true },
  { roleCode: 'WORKER', permissionCode: 'identity:read:own', isBaseline: true },
  { roleCode: 'WORKER', permissionCode: 'identity:update:own', isBaseline: true },
  { roleCode: 'WORKER', permissionCode: 'project:list:assigned', isBaseline: true },
  { roleCode: 'WORKER', permissionCode: 'project:read:assigned', isBaseline: true },
  { roleCode: 'WORKER', permissionCode: 'task:list:assigned', isBaseline: true },
  { roleCode: 'WORKER', permissionCode: 'task:read:assigned', isBaseline: true },
  { roleCode: 'WORKER', permissionCode: 'task:update:own', isBaseline: true },
  { roleCode: 'WORKER', permissionCode: 'expenses:create:own', isBaseline: true },
  { roleCode: 'WORKER', permissionCode: 'expenses:list:own', isBaseline: true },
  { roleCode: 'WORKER', permissionCode: 'expenses:read:own', isBaseline: true },
  { roleCode: 'WORKER', permissionCode: 'time:read:own', isBaseline: true },
  { roleCode: 'WORKER', permissionCode: 'time:create:own_entry', isBaseline: true },
  { roleCode: 'WORKER', permissionCode: 'scheduling:read:own', isBaseline: true },
  { roleCode: 'WORKER', permissionCode: 'documents:list:assigned', isBaseline: true },
  { roleCode: 'WORKER', permissionCode: 'documents:read:assigned', isBaseline: true },
  { roleCode: 'WORKER', permissionCode: 'documents:upload:assigned', isBaseline: true },
  { roleCode: 'WORKER', permissionCode: 'ai:ask', isBaseline: true },
  { roleCode: 'WORKER', permissionCode: 'ai:assist:task', isBaseline: true },
  { roleCode: 'DRIVER', permissionCode: 'identity:read:own', isBaseline: true },
  { roleCode: 'DRIVER', permissionCode: 'identity:update:own', isBaseline: true },
  { roleCode: 'DRIVER', permissionCode: 'project:list:delivery_assigned', isBaseline: true },
  { roleCode: 'DRIVER', permissionCode: 'project:read:delivery_info', isBaseline: true },
  { roleCode: 'DRIVER', permissionCode: 'task:list:delivery', isBaseline: true },
  { roleCode: 'DRIVER', permissionCode: 'task:read:delivery', isBaseline: true },
  { roleCode: 'DRIVER', permissionCode: 'task:update:delivery', isBaseline: true },
  { roleCode: 'DRIVER', permissionCode: 'inventory:read:delivery_items', isBaseline: true },
  { roleCode: 'DRIVER', permissionCode: 'expenses:create:delivery', isBaseline: true },
  { roleCode: 'DRIVER', permissionCode: 'expenses:list:own', isBaseline: true },
  { roleCode: 'DRIVER', permissionCode: 'expenses:read:own', isBaseline: true },
  { roleCode: 'DRIVER', permissionCode: 'time:read:own', isBaseline: true },
  { roleCode: 'DRIVER', permissionCode: 'time:create:own_entry', isBaseline: true },
  { roleCode: 'DRIVER', permissionCode: 'scheduling:read:own', isBaseline: true },
  { roleCode: 'DRIVER', permissionCode: 'documents:upload:delivery', isBaseline: true },
  { roleCode: 'DRIVER', permissionCode: 'documents:read:delivery', isBaseline: true },
  { roleCode: 'DRIVER', permissionCode: 'ai:ask', isBaseline: true },
  { roleCode: 'DRIVER', permissionCode: 'ai:assist:delivery', isBaseline: true },
  { roleCode: 'VIEWER', permissionCode: 'estimate:read', isBaseline: true },
  { roleCode: 'VIEWER', permissionCode: 'estimate:list', isBaseline: true },
  { roleCode: 'VIEWER', permissionCode: 'invoice:read', isBaseline: true },
  { roleCode: 'VIEWER', permissionCode: 'invoice:list', isBaseline: true },
  { roleCode: 'VIEWER', permissionCode: 'project:read', isBaseline: true },
  { roleCode: 'VIEWER', permissionCode: 'project:list', isBaseline: true },
  { roleCode: 'VIEWER', permissionCode: 'crm:read', isBaseline: true },
  { roleCode: 'VIEWER', permissionCode: 'crm:list', isBaseline: true },
  { roleCode: 'VIEWER', permissionCode: 'inventory:read', isBaseline: true },
  { roleCode: 'VIEWER', permissionCode: 'inventory:list', isBaseline: true },
  { roleCode: 'VIEWER', permissionCode: 'expenses:read', isBaseline: true },
  { roleCode: 'VIEWER', permissionCode: 'expenses:list', isBaseline: true },
  { roleCode: 'VIEWER', permissionCode: 'scheduling:read', isBaseline: true },
  { roleCode: 'VIEWER', permissionCode: 'time:read:own', isBaseline: true },
  { roleCode: 'VIEWER', permissionCode: 'payroll:read:own', isBaseline: true },
  { roleCode: 'VIEWER', permissionCode: 'documents:read', isBaseline: true },
  { roleCode: 'VIEWER', permissionCode: 'documents:list', isBaseline: true },
  { roleCode: 'VIEWER', permissionCode: 'ai:ask', isBaseline: true },
  { roleCode: 'VIEWER', permissionCode: 'ai:generate:demo_report', isBaseline: true },
  { roleCode: 'CLIENT_OWNER', permissionCode: 'project:read:assigned', isBaseline: true },
  { roleCode: 'CLIENT_OWNER', permissionCode: 'invoice:read:own', isBaseline: true },
  { roleCode: 'CLIENT_OWNER', permissionCode: 'documents:read:assigned', isBaseline: true },
  { roleCode: 'CLIENT_MANAGER', permissionCode: 'project:read:assigned', isBaseline: true },
  { roleCode: 'CLIENT_MANAGER', permissionCode: 'documents:read:assigned', isBaseline: true },
  { roleCode: 'CLIENT_VIEWER', permissionCode: 'project:read:assigned', isBaseline: true },
  { roleCode: 'VENDOR', permissionCode: 'project:read:assigned', isBaseline: true },
  { roleCode: 'VENDOR', permissionCode: 'inventory:read', isBaseline: true },
  { roleCode: 'VENDOR', permissionCode: 'documents:read:assigned', isBaseline: true },
  { roleCode: 'GUEST', permissionCode: 'project:read', isBaseline: true },
  { roleCode: 'GUEST', permissionCode: 'documents:read', isBaseline: true },
];

// ============================================================================
// DOMAIN SEED DATA
// ============================================================================

export const domainSeeds = [
  {
    code: 'tenant',
    name: 'Tenant',
    description: 'Tenant management and configuration',
  },
  {
    code: 'identity',
    name: 'Identity',
    description: 'User and actor identity management',
  },
  {
    code: 'membership',
    name: 'Membership',
    description: 'Member management and role assignment',
  },
  {
    code: 'accesscontrol',
    name: 'Accesscontrol',
    description: 'Role and permission management',
  },
  {
    code: 'estimate',
    name: 'Estimate',
    description: 'Estimate and proposal management',
  },
  {
    code: 'invoice',
    name: 'Invoice',
    description: 'Invoice and billing management',
  },
  {
    code: 'project',
    name: 'Project',
    description: 'Project management and execution',
  },
  {
    code: 'task',
    name: 'Task',
    description: 'Task management and assignment',
  },
  {
    code: 'expenses',
    name: 'Expenses',
    description: 'Expense tracking and reimbursement',
  },
  {
    code: 'time',
    name: 'Time',
    description: 'Time tracking and timesheets',
  },
  {
    code: 'scheduling',
    name: 'Scheduling',
    description: 'Resource and time scheduling',
  },
  {
    code: 'payroll',
    name: 'Payroll',
    description: 'Payroll processing and management',
  },
  {
    code: 'inventory',
    name: 'Inventory',
    description: 'Materials and stock management',
  },
  {
    code: 'crm',
    name: 'Crm',
    description: 'Customer relationship management',
  },
  {
    code: 'documents',
    name: 'Documents',
    description: 'Document and file management',
  },
  {
    code: 'ai',
    name: 'Ai',
    description: 'AI assistance and automation',
  },
  {
    code: 'analytics',
    name: 'Analytics',
    description: 'Business intelligence and KPIs',
  },
];

// ============================================================================
// SEED EXECUTION FUNCTIONS
// ============================================================================

/**
 * Seed roles
 */
export async function seedRoles() {
  console.log('🔄 Seeding roles...');

  for (const roleData of roleSeeds) {
    await prisma.role.upsert({
      where: { code: roleData.code },
      update: {
        name: roleData.name,
        description: roleData.description,
        hierarchy: roleData.hierarchy,
        roleType: roleData.roleType,
        isActive: roleData.isActive,
      },
      create: roleData,
    });
  }

  console.log(`✅ Seeded ${roleSeeds.length} roles`);
}

/**
 * Seed permissions
 */
export async function seedPermissions() {
  console.log('🔄 Seeding permissions...');

  for (const permissionData of permissionSeeds) {
    await prisma.permission.upsert({
      where: { code: permissionData.code },
      update: {
        domain: permissionData.domain,
        action: permissionData.action,
        subaction: permissionData.subaction,
        description: permissionData.description,
        isBaseline: permissionData.isBaseline,
        isCritical: permissionData.isCritical,
      },
      create: permissionData,
    });
  }

  console.log(`✅ Seeded ${permissionSeeds.length} permissions`);
}

/**
 * Seed domains
 */
export async function seedDomains() {
  console.log('🔄 Seeding domains...');

  for (const domainData of domainSeeds) {
    await prisma.domain.upsert({
      where: { code: domainData.code },
      update: {
        name: domainData.name,
        description: domainData.description,
      },
      create: domainData,
    });
  }

  console.log(`✅ Seeded ${domainSeeds.length} domains`);
}

/**
 * Seed role permissions (baseline only)
 */
export async function seedRolePermissions() {
  console.log('🔄 Seeding role permissions...');

  // Clear existing role permissions
  await prisma.rolePermission.deleteMany({});

  for (const rpData of rolePermissionSeeds) {
    await prisma.rolePermission.create({
      data: {
        role: { connect: { code: rpData.roleCode } },
        permission: { connect: { code: rpData.permissionCode } },
        isBaseline: rpData.isBaseline,
      },
    });
  }

  console.log(`✅ Seeded ${rolePermissionSeeds.length} role permissions`);
}

/**
 * Main seed function
 */
export async function seedRBAC() {
  try {
    console.log('🚀 Starting RBAC Phase 1 seed...');

    await seedDomains();
    await seedRoles();
    await seedPermissions();
    await seedRolePermissions();

    console.log('✅ RBAC Phase 1 seed completed successfully!');
    console.log(`📊 Summary: ${roleSeeds.length} roles, ${permissionSeeds.length} permissions, ${rolePermissionSeeds.length} grants`);

  } catch (error) {
    console.error('❌ RBAC seed failed:', error);
    throw error;
  } finally {
    await prisma.$disconnect();
  }
}

// Run seed if called directly
if (require.main === module) {
  seedRBAC().catch(console.error);
}

export default {
  roleSeeds,
  permissionSeeds,
  rolePermissionSeeds,
  domainSeeds,
  seedRoles,
  seedPermissions,
  seedDomains,
  seedRolePermissions,
  seedRBAC,
};
