// scripts/generate-tables.ts
// Generate a single Prisma file from Tables.v2.md lists (Hybrid/Global/Tenant)
// Usage:
//   npx tsx scripts/generate-tables.ts --input ./Tables.v2.md --outFile prisma/schemas/generated/models.generated.prisma --snake
//
// Flags:
//   --input <path>     Path to Tables.v2.md (default: ./Tables.v2.md)
//   --outFile <path>   Single output file (default: prisma/schemas/generated/models.generated.prisma)
//   --snake            Adds @@map("snake_case") per model
//
// Notes:
// - Templates follow enterprise best practices (Nov-2025).
// - Actor relations are not created by default (UUIDs only). Enable them manually for CRITICAL PARENT entities.
// - For BH, generates tenantId + globalId and @@unique([tenantId, globalId]).
// - For BT, generates @@unique([tenantId, id]) and Tenant @ Cascade relation (commented placeholder).
// - For BG, no tenantId; includes basic operational indexes.
//
// Tip: Keep generator/datasource in prisma/schemas/_base.prisma

import * as fs from "node:fs/promises";
import * as path from "node:path";

type Bucket = "HYBRID" | "GLOBAL" | "TENANT";

const argv = process.argv.slice(2);
function getFlag(name: string, def?: string) {
    const i = argv.indexOf(`--${name}`);
    if (i !== -1) return argv[i + 1];
    return def;
}
function hasFlag(name: string) {
    return argv.includes(`--${name}`);
}

const INPUT = getFlag("input", path.join(process.cwd(), "Tables.v2.md"))!;
const OUTFILE =
    getFlag("outFile") ?? path.join(process.cwd(), "prisma/schemas/generated/models.generated.prisma");
const USE_SNAKE = hasFlag("snake");

const HEADER = `// ======================================================================
// AUTOGENERATED FILE - DO NOT EDIT DIRECTLY
// Generated by scripts/generate-tables.ts
// Standard: ERP Multitenant (Nov-2025) BT/BH/BG base fields
// ======================================================================

`;

const templateBT = (model: string, snake?: boolean) => `model ${model} {
    // 🆔 Identity & Tenant
  id       String @id @default(uuid(7)) @db.Uuid
  tenantId String @db.Uuid

    // 📊 Lifecycle
  status    String   @default("ACTIVE")
  version   Int      @default(1)
  createdAt DateTime @default(now()) @db.Timestamptz(6)
  updatedAt DateTime @updatedAt       @db.Timestamptz(6)
  deletedAt DateTime?                 @db.Timestamptz(6)

    // 👤 Minimal audit (UUIDs; Actor relations only for CRITICAL PARENT entities)
  createdByActorId String? @db.Uuid
  updatedByActorId String? @db.Uuid
  deletedByActorId String? @db.Uuid

    // 🧠 Governance
  auditCorrelationId String? @db.Uuid
  dataClassification String   @default("INTERNAL") @db.VarChar(50)
  // retentionPolicy    RetentionPolicy?  // descomenta si tu módulo lo usa

    // 🔎 Observability (OPTIONAL: enable only if it adds real value)
  // traceId      String? @db.VarChar(64)
  // spanId       String? @db.VarChar(32)
  // authContext  String? @db.Text
    // hashToken    String? @db.VarChar(255) // add per-tenant index if you query it
  // metadata     Json?   @db.JsonB
    // recordSource String? @db.VarChar(50)  // API, IMPORT, SYSTEM
  // timezone     String? @db.VarChar(50)

    // 🔗 Required relations
  // tenant Tenant @relation("TenantTo${model}", fields: [tenantId], references: [id], onDelete: Cascade)

    // 👥 Actor relations (ENABLE ONLY for CRITICAL PARENT entities)
  // createdByActor Actor? @relation("${model}CreatedByActor", fields: [createdByActorId], references: [id], onDelete: SetNull)
  // updatedByActor Actor? @relation("${model}UpdatedByActor", fields: [updatedByActorId], references: [id], onDelete: SetNull)
  // deletedByActor Actor? @relation("${model}DeletedByActor", fields: [deletedByActorId], references: [id], onDelete: SetNull)

    // 🗂️ Indexes & constraints (tenant-first)
  @@unique([tenantId, id])
  @@index([tenantId, status])
  @@index([tenantId, deletedAt])
  @@index([createdAt], type: Brin)
  @@index([tenantId, auditCorrelationId])
  @@index([tenantId, dataClassification])

    // Enable ONLY if you use these fields:
  // @@index([tenantId, hashToken])
  // @@index([tenantId, recordSource])
  // @@index([tenantId, timezone])
  // @@index([metadata], type: Gin)
${snake ? `\n  @@map("${toSnake(model)}")\n` : ""}}`;

const templateBH = (model: string, snake?: boolean) => `model ${model} {
    // 🆔 Identity, Tenant and Global
  id       String @id @default(uuid(7)) @db.Uuid
  tenantId String @db.Uuid
  globalId String @db.Uuid   // referencia a entidad BG

    // 📊 Lifecycle
  status    String   @default("ACTIVE")
  version   Int      @default(1)
  createdAt DateTime @default(now()) @db.Timestamptz(6)
  updatedAt DateTime @updatedAt       @db.Timestamptz(6)
  deletedAt DateTime?                 @db.Timestamptz(6)

    // 👤 Minimal audit (UUIDs; Actor relations only for CRITICAL PARENT entities)
  createdByActorId String? @db.Uuid
  updatedByActorId String? @db.Uuid
  deletedByActorId String? @db.Uuid

    // 🧠 Governance
  auditCorrelationId String? @db.Uuid
  dataClassification String   @default("CONFIDENTIAL") @db.VarChar(50)

    // 🔎 Observability (OPTIONAL)
  // traceId      String? @db.VarChar(64)
  // spanId       String? @db.VarChar(32)
  // authContext  String? @db.Text
  // hashToken    String? @db.VarChar(255)
  // metadata     Json?   @db.JsonB
  // recordSource String? @db.VarChar(50)
  // timezone     String? @db.VarChar(50)

    // 🔗 Required relations
  // tenant Tenant @relation("TenantTo${model}", fields: [tenantId], references: [id], onDelete: Cascade)

    // Relation to the Global entity (adjust the real BG model)
  // global <YourGlobalModel> @relation(fields: [globalId], references: [id], onDelete: Restrict)

    // 👥 Actor relations (ENABLE ONLY for CRITICAL PARENT entities)
  // createdByActor Actor? @relation("${model}CreatedByActor", fields: [createdByActorId], references: [id], onDelete: SetNull)
  // updatedByActor Actor? @relation("${model}UpdatedByActor", fields: [updatedByActorId], references: [id], onDelete: SetNull)
  // deletedByActor Actor? @relation("${model}DeletedByActor", fields: [deletedByActorId], references: [id], onDelete: SetNull)

    // 🗂️ Indexes & constraints
  @@unique([tenantId, globalId])   // un override por globalId en cada tenant
  @@index([globalId])
  @@index([tenantId, status])
  @@index([tenantId, deletedAt])
  @@index([createdAt], type: Brin)
  @@index([tenantId, auditCorrelationId])
  @@index([tenantId, dataClassification])

    // Enable ONLY if you use these fields:
  // @@index([tenantId, hashToken])
  // @@index([tenantId, recordSource])
  // @@index([tenantId, timezone])
  // @@index([metadata], type: Gin)
${snake ? `\n  @@map("${toSnake(model)}")\n` : ""}}`;

const templateBG = (model: string, snake?: boolean) => `model ${model} {
    // 🆔 Identity
  id String @id @default(uuid(7)) @db.Uuid

    // 📊 Lifecycle
  status    String   @default("ACTIVE")
  version   Int      @default(1)
  createdAt DateTime @default(now()) @db.Timestamptz(6)
  updatedAt DateTime @updatedAt       @db.Timestamptz(6)
  deletedAt DateTime?                 @db.Timestamptz(6)

    // 👤 Minimal audit (UUIDs; Actor relations only if it's a critical global entity)
  createdByActorId String? @db.Uuid
  updatedByActorId String? @db.Uuid
  deletedByActorId String? @db.Uuid

    // 🧠 Governance
  auditCorrelationId String? @db.Uuid
  dataClassification String   @default("PUBLIC") @db.VarChar(50)
  // retentionPolicy    RetentionPolicy?

    // 🔎 Observability (OPTIONAL)
  // traceId      String? @db.VarChar(64)
  // spanId       String? @db.VarChar(32)
  // authContext  String? @db.Text
  // hashToken    String? @db.VarChar(255)
  // metadata     Json?   @db.JsonB
  // recordSource String? @db.VarChar(50)

    // 🗂️ Indexes & constraints (no tenant)
  @@index([status])
  @@index([deletedAt])
  @@index([createdAt], type: Brin)
  @@index([auditCorrelationId])
  @@index([dataClassification])

    // Enable ONLY if you use these fields:
  // @@index([hashToken])
  // @@index([recordSource])
  // @@index([metadata], type: Gin)
${snake ? `\n  @@map("${toSnake(model)}")\n` : ""}}`;

const SECTION_HEADERS = {
    HYBRID: /^##\s*Hybrid Tables/i,
    GLOBAL: /^##\s*Global Tables/i,
    TENANT: /^##\s*Tenant Tables/i,
};

function toSnake(name: string) {
    return name
        .replace(/([a-z0-9])([A-Z])/g, "$1_$2")
        .replace(/[\s-]+/g, "_")
        .toLowerCase();
}

function clean(line: string) {
    return line
        .replace(/^-\s+/, "") // Remove markdown list prefix "- "
        .replace(/^\*\*?table_name:?\*\*?$/i, "")
        .replace(/^[-_]+$/, "")
        .replace(/^\s*\/\/.*$/, "")
        .trim();
}

function isModelName(s: string) {
    if (!s) return false;
    // discard lines that are clearly not identifiers
    if (/^\s*$/i.test(s)) return false;
    if (/^[#<*-]/.test(s)) return false;
    if (/^[-_*]+$/.test(s)) return false;
    // avoid comments, descriptions, or inline notes
    if (s.includes("alias") || s.includes("uso") || s.includes("típicos") || s.includes("Casos")) return false;
    if (s.includes("Integración") || s.includes("URLs") || s.includes("Funcionalidad") || s.includes("Comunicaciones") || s.includes("APIs")) return false;
    if (s.includes("Gestión") || s.includes("Configuración") || s.includes("Modelos") || s.includes("sistema")) return false;
    if (s.includes("Datos") || s.includes("Proyectos") || s.includes("Inventario") || s.includes("Empleados")) return false;
    // simple allowlist: letters, numbers, underscores (Prisma model name)
    return /^[A-Z][A-Za-z0-9_]*$/.test(s);
}

async function parseTablesMd(file: string) {
    const raw = await fs.readFile(file, "utf8");
    const lines = raw.split(/\r?\n/);

    let mode: Bucket | null = null;
    const hybrid = new Set<string>();
    const global = new Set<string>();
    const tenant = new Set<string>();

    for (const rawLine of lines) {
        const line = rawLine.trim();

        if (SECTION_HEADERS.HYBRID.test(line)) {
            mode = "HYBRID";
            continue;
        }
        if (SECTION_HEADERS.GLOBAL.test(line)) {
            mode = "GLOBAL";
            continue;
        }
        if (SECTION_HEADERS.TENANT.test(line)) {
            mode = "TENANT";
            continue;
        }

        const t = clean(line);
        if (!isModelName(t)) continue;

        if (mode === "HYBRID") hybrid.add(t);
        else if (mode === "GLOBAL") global.add(t);
        else if (mode === "TENANT") tenant.add(t);
    }

    // sanity: remove accidental duplicates across buckets, preferring HYBRID > GLOBAL > TENANT
    for (const m of hybrid) {
        global.delete(m);
        tenant.delete(m);
    }
    for (const m of global) {
        tenant.delete(m);
    }

    return { hybrid: [...hybrid].sort(), global: [...global].sort(), tenant: [...tenant].sort() };
}

async function ensureDir(p: string) {
    await fs.mkdir(p, { recursive: true });
}

function renderModel(name: string, bucket: Bucket, snake: boolean) {
    switch (bucket) {
        case "TENANT":
            return templateBT(name, snake);
        case "HYBRID":
            return templateBH(name, snake);
        case "GLOBAL":
            return templateBG(name, snake);
    }
}

async function main() {
    const { hybrid, global, tenant } = await parseTablesMd(INPUT);

    // Prepare single-file content
    const outDir = path.dirname(OUTFILE);
    await ensureDir(outDir);

    const headerMeta = `// Source: ${path.relative(process.cwd(), INPUT)}\n// Generated: ${new Date().toISOString()}\n`;

    const parts: string[] = [];
    parts.push(HEADER + headerMeta);
    if (hybrid.length) {
        parts.push(`// ======================================================\n// BH — Base Hybrid (tenant + global)\n// Count: ${hybrid.length}\n// ======================================================\n`);
        for (const m of hybrid) parts.push(renderModel(m, "HYBRID", USE_SNAKE));
    }
    if (global.length) {
        parts.push(`// ======================================================\n// BG — Base Global (shared masters)\n// Count: ${global.length}\n// ======================================================\n`);
        for (const m of global) parts.push(renderModel(m, "GLOBAL", USE_SNAKE));
    }
    if (tenant.length) {
        parts.push(`// ======================================================\n// BT — Base Tenant (tenant-scoped)\n// Count: ${tenant.length}\n// ======================================================\n`);
        for (const m of tenant) parts.push(renderModel(m, "TENANT", USE_SNAKE));
    }

    const content = parts.join("\n\n") + "\n";
    await fs.writeFile(OUTFILE, content, "utf8");

    console.log("✅ Generation complete (single file).");
    console.log(`   Hybrid (BH): ${hybrid.length}`);
    console.log(`   Global (BG): ${global.length}`);
    console.log(`   Tenant (BT): ${tenant.length}`);
    console.log(`   Output file: ${path.relative(process.cwd(), OUTFILE)}`);
}

main().catch((err) => {
    console.error("❌ Generation failed:", err);
    process.exit(1);
});
