/**
 * 🏛️ RBAC Constants - AUTO-GENERATED
 * 
 * Generated: 2025-11-18T21:20:30.339Z
 * Phase: Phase 1 - Internal Members Only
 * Source: rbac_schema_v9.0.yml
 * Generator: rbac-generator-v9.0.ts
 * 
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * Regenerate using: npx tsx rbac-generator-v9.0.ts
 */

// ============================================================================
// ROLE CODES - Phase 1 Internal Members
// ============================================================================

export const ROLE_CODES = {
  // Tenant Owner (Hierarchy 0)
  ADMIN: "ADMIN",
  
  // Scoped Manager (Hierarchy 2)
  PROJECT_MANAGER: "PROJECT_MANAGER",
  
  // Execution Roles (Hierarchy 8-9)
  WORKER: "WORKER",
  DRIVER: "DRIVER",
  
  // Read-Only Sandbox (Hierarchy 10)
  VIEWER: "VIEWER",
} as const;

export type RoleCode = (typeof ROLE_CODES)[keyof typeof ROLE_CODES];

// ============================================================================
// ROLE HIERARCHY - 0 is Highest Authority
// ============================================================================

export const ROLE_HIERARCHY: Record<RoleCode, number> = {
  ADMIN: 0,
  PROJECT_MANAGER: 2,
  WORKER: 8,
  DRIVER: 9,
  VIEWER: 10,
} as const;

// ============================================================================
// ROLE METADATA
// ============================================================================

export interface RoleMetadata {
  code: RoleCode;
  hierarchy: number;
  displayName: string;
  description: string;
  roleType: "INTERNAL" | "EXTERNAL";
}

export const ROLE_METADATA: Record<RoleCode, RoleMetadata> = {
  ADMIN: {
    code: "ADMIN",
    hierarchy: 0,
    displayName: "Administrator",
    description: "Tenant owner with full control of business data and tenant configuration within their tenant",
    roleType: "INTERNAL",
  },
  PROJECT_MANAGER: {
    code: "PROJECT_MANAGER",
    hierarchy: 2,
    displayName: "Project Manager",
    description: "Scoped manager responsible for own/assigned projects, estimates, invoices, and teams",
    roleType: "INTERNAL",
  },
  WORKER: {
    code: "WORKER",
    hierarchy: 8,
    displayName: "Field Worker",
    description: "Field or office execution role working on assigned projects and tasks",
    roleType: "INTERNAL",
  },
  DRIVER: {
    code: "DRIVER",
    hierarchy: 9,
    displayName: "Driver",
    description: "Delivery and logistics role with minimal access to delivery-related information",
    roleType: "INTERNAL",
  },
  VIEWER: {
    code: "VIEWER",
    hierarchy: 10,
    displayName: "Viewer",
    description: "Read-only role for demos and learning in sandbox tenants only",
    roleType: "INTERNAL",
  },
} as const;

// ============================================================================
// DOMAIN CODES
// ============================================================================

export const DOMAINS = {
  TENANT: "tenant",
  ACCESSCONTROL: "accesscontrol",
  IDENTITY: "identity",
  MEMBERSHIP: "membership",
  ESTIMATE: "estimate",
  INVOICE: "invoice",
  PROJECT: "project",
  TASK: "task",
  EXPENSES: "expenses",
  INVENTORY: "inventory",
  SCHEDULING: "scheduling",
  TIME: "time",
  PAYROLL: "payroll",
  CRM: "crm",
  DOCUMENTS: "documents",
  CHANGEORDER: "changeorder",
  AI: "ai",
  ANALYTICS: "analytics",
} as const;

export type Domain = (typeof DOMAINS)[keyof typeof DOMAINS];

// ============================================================================
// PERMISSION CONSTANTS - Complete Catalog
// ============================================================================

export const PERMISSIONS = {
  // ACCESSCONTROL Domain
  ACCESSCONTROL_MANAGE_SERVICE_ACCOUNTS: "accesscontrol:manage:service_accounts",
  ACCESSCONTROL_READ: "accesscontrol:read",
  ACCESSCONTROL_UPDATE_TENANT_ROLES: "accesscontrol:update:tenant_roles",

  // AI Domain
  AI_ASK: "ai:ask",
  AI_ASSIST_DELIVERY: "ai:assist:delivery",
  AI_ASSIST_PROJECT: "ai:assist:project",
  AI_ASSIST_TASK: "ai:assist:task",
  AI_ASSIST_TENANT: "ai:assist:tenant",
  AI_GENERATE_DEMO_REPORT: "ai:generate:demo_report",
  AI_GENERATE_FINANCIAL_REPORT: "ai:generate:financial_report",
  AI_GENERATE_PROJECT_REPORT: "ai:generate:project_report",

  // ANALYTICS Domain
  ANALYTICS_READ_TENANT_KPIS: "analytics:read:tenant_kpis",

  // CHANGEORDER Domain
  CHANGEORDER_APPROVE: "changeorder:approve",
  CHANGEORDER_DELETE_OWN: "changeorder:delete:own",

  // CRM Domain
  CRM_CREATE: "crm:create",
  CRM_DELETE: "crm:delete",
  CRM_LIST: "crm:list",
  CRM_READ: "crm:read",
  CRM_UPDATE: "crm:update",

  // DOCUMENTS Domain
  DOCUMENTS_COMMENT_PROJECT: "documents:comment:project",
  DOCUMENTS_CREATE: "documents:create",
  DOCUMENTS_DELETE: "documents:delete",
  DOCUMENTS_LIST: "documents:list",
  DOCUMENTS_LIST_ASSIGNED: "documents:list:assigned",
  DOCUMENTS_LIST_PROJECT: "documents:list:project",
  DOCUMENTS_READ: "documents:read",
  DOCUMENTS_READ_ASSIGNED: "documents:read:assigned",
  DOCUMENTS_READ_DELIVERY: "documents:read:delivery",
  DOCUMENTS_READ_PROJECT: "documents:read:project",
  DOCUMENTS_UPDATE: "documents:update",
  DOCUMENTS_UPLOAD_ASSIGNED: "documents:upload:assigned",
  DOCUMENTS_UPLOAD_DELIVERY: "documents:upload:delivery",
  DOCUMENTS_UPLOAD_PROJECT: "documents:upload:project",

  // ESTIMATE Domain
  ESTIMATE_APPROVE: "estimate:approve",
  ESTIMATE_CREATE: "estimate:create",
  ESTIMATE_DELETE: "estimate:delete",
  ESTIMATE_DELETE_OWN: "estimate:delete:own",
  ESTIMATE_LIST: "estimate:list",
  ESTIMATE_LIST_OWN: "estimate:list:own",
  ESTIMATE_READ: "estimate:read",
  ESTIMATE_READ_OWN: "estimate:read:own",
  ESTIMATE_READ_PROFIT: "estimate:read:profit",
  ESTIMATE_SEND: "estimate:send",
  ESTIMATE_SEND_OWN: "estimate:send:own",
  ESTIMATE_UPDATE: "estimate:update",
  ESTIMATE_UPDATE_OWN: "estimate:update:own",

  // EXPENSES Domain
  EXPENSES_APPROVE: "expenses:approve",
  EXPENSES_CREATE: "expenses:create",
  EXPENSES_CREATE_DELIVERY: "expenses:create:delivery",
  EXPENSES_CREATE_OWN: "expenses:create:own",
  EXPENSES_DELETE: "expenses:delete",
  EXPENSES_LIST: "expenses:list",
  EXPENSES_LIST_OWN: "expenses:list:own",
  EXPENSES_LIST_PROJECT: "expenses:list:project",
  EXPENSES_READ: "expenses:read",
  EXPENSES_READ_OWN: "expenses:read:own",
  EXPENSES_READ_PROJECT: "expenses:read:project",
  EXPENSES_UPDATE: "expenses:update",

  // IDENTITY Domain
  IDENTITY_INVITE_USER: "identity:invite:user",
  IDENTITY_READ_TENANT_USERS: "identity:read:tenant_users",
  IDENTITY_UPDATE_TENANT_USERS: "identity:update:tenant_users",

  // INVENTORY Domain
  INVENTORY_ADJUST_QUANTITY: "inventory:adjust:quantity",
  INVENTORY_CREATE_ITEM: "inventory:create:item",
  INVENTORY_INVESTIGATE_LOSS: "inventory:investigate:loss",
  INVENTORY_LIST: "inventory:list",
  INVENTORY_READ: "inventory:read",
  INVENTORY_READ_DELIVERY_ITEMS: "inventory:read:delivery_items",
  INVENTORY_UPDATE_ITEM: "inventory:update:item",

  // INVOICE Domain
  INVOICE_APPROVE: "invoice:approve",
  INVOICE_CREATE: "invoice:create",
  INVOICE_DELETE: "invoice:delete",
  INVOICE_DELETE_OWN: "invoice:delete:own",
  INVOICE_LIST: "invoice:list",
  INVOICE_LIST_OWN: "invoice:list:own",
  INVOICE_READ: "invoice:read",
  INVOICE_READ_OWN: "invoice:read:own",
  INVOICE_READ_PROFIT: "invoice:read:profit",
  INVOICE_SEND: "invoice:send",
  INVOICE_SEND_OWN: "invoice:send:own",
  INVOICE_UPDATE: "invoice:update",
  INVOICE_UPDATE_OWN: "invoice:update:own",
  INVOICE_WRITEOFF: "invoice:writeoff",

  // MEMBERSHIP Domain
  MEMBERSHIP_MANAGE_ROLES: "membership:manage:roles",
  MEMBERSHIP_READ_TENANT_MEMBERS: "membership:read:tenant_members",
  MEMBERSHIP_UPDATE_TENANT_MEMBERS: "membership:update:tenant_members",

  // PAYROLL Domain
  PAYROLL_READ: "payroll:read",
  PAYROLL_READ_OWN: "payroll:read:own",
  PAYROLL_READ_TENANT: "payroll:read:tenant",
  PAYROLL_RUN: "payroll:run",
  PAYROLL_UPDATE: "payroll:update",

  // PROJECT Domain
  PROJECT_ASSIGN_DRIVER: "project:assign:driver",
  PROJECT_ASSIGN_PM: "project:assign:pm",
  PROJECT_ASSIGN_TASK: "project:assign:task",
  PROJECT_ASSIGN_WORKER: "project:assign:worker",
  PROJECT_CREATE: "project:create",
  PROJECT_CREATE_OWN: "project:create:own",
  PROJECT_DELETE: "project:delete",
  PROJECT_LIST: "project:list",
  PROJECT_LIST_ASSIGNED: "project:list:assigned",
  PROJECT_LIST_DELIVERY_ASSIGNED: "project:list:delivery_assigned",
  PROJECT_LIST_OWN: "project:list:own",
  PROJECT_READ: "project:read",
  PROJECT_READ_ASSIGNED: "project:read:assigned",
  PROJECT_READ_DELIVERY_INFO: "project:read:delivery_info",
  PROJECT_READ_FINANCIAL: "project:read:financial",
  PROJECT_READ_OWN: "project:read:own",
  PROJECT_READ_SCHEDULE: "project:read:schedule",
  PROJECT_READ_TEAM: "project:read:team",
  PROJECT_UPDATE: "project:update",
  PROJECT_UPDATE_OWN: "project:update:own",

  // SCHEDULING Domain
  SCHEDULING_CREATE: "scheduling:create",
  SCHEDULING_READ: "scheduling:read",
  SCHEDULING_READ_OWN: "scheduling:read:own",
  SCHEDULING_UPDATE: "scheduling:update",

  // TASK Domain
  TASK_ASSIGN_DRIVER: "task:assign:driver",
  TASK_ASSIGN_WORKER: "task:assign:worker",
  TASK_CREATE: "task:create",
  TASK_CREATE_PROJECT: "task:create:project",
  TASK_DELETE: "task:delete",
  TASK_LIST: "task:list",
  TASK_LIST_ASSIGNED: "task:list:assigned",
  TASK_LIST_DELIVERY: "task:list:delivery",
  TASK_LIST_PROJECT: "task:list:project",
  TASK_READ: "task:read",
  TASK_READ_ASSIGNED: "task:read:assigned",
  TASK_READ_DELIVERY: "task:read:delivery",
  TASK_READ_PROJECT: "task:read:project",
  TASK_UPDATE: "task:update",
  TASK_UPDATE_DELIVERY: "task:update:delivery",
  TASK_UPDATE_OWN: "task:update:own",
  TASK_UPDATE_PROJECT: "task:update:project",

  // TENANT Domain
  TENANT_MANAGE_FEATURES: "tenant:manage:features",
  TENANT_MANAGE_MODULES: "tenant:manage:modules",
  TENANT_READ: "tenant:read",
  TENANT_UPDATE: "tenant:update",

  // TIME Domain
  TIME_CORRECT_TENANT: "time:correct:tenant",
  TIME_CREATE_OWN_ENTRY: "time:create:own_entry",
  TIME_READ: "time:read",
  TIME_READ_OWN: "time:read:own",
  TIME_READ_TENANT: "time:read:tenant",
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

// ============================================================================
// ROLE PERMISSIONS - Baseline Grants
// ============================================================================

export const ROLE_PERMISSIONS: Record<RoleCode, readonly Permission[]> = {
  ADMIN: [
    "tenant:read",
    "tenant:update",
    "tenant:manage:modules",
    "tenant:manage:features",
    "identity:invite:user",
    "identity:read:tenant_users",
    "identity:update:tenant_users",
    "membership:manage:roles",
    "membership:read:tenant_members",
    "membership:update:tenant_members",
    "accesscontrol:read",
    "accesscontrol:update:tenant_roles",
    "accesscontrol:manage:service_accounts",
    "estimate:create",
    "estimate:list",
    "estimate:read",
    "estimate:update",
    "estimate:delete",
    "estimate:send",
    "estimate:approve",
    "invoice:create",
    "invoice:list",
    "invoice:read",
    "invoice:update",
    "invoice:delete",
    "invoice:send",
    "invoice:approve",
    "invoice:writeoff",
    "project:create",
    "project:list",
    "project:read",
    "project:update",
    "project:delete",
    "project:assign:pm",
    "project:assign:worker",
    "project:assign:driver",
    "project:read:financial",
    "task:create",
    "task:list",
    "task:read",
    "task:update",
    "task:delete",
    "task:assign:worker",
    "task:assign:driver",
    "expenses:create",
    "expenses:list",
    "expenses:read",
    "expenses:update",
    "expenses:delete",
    "expenses:approve",
    "inventory:create:item",
    "inventory:list",
    "inventory:read",
    "inventory:update:item",
    "inventory:adjust:quantity",
    "inventory:investigate:loss",
    "scheduling:create",
    "scheduling:read",
    "scheduling:update",
    "time:read:tenant",
    "time:correct:tenant",
    "payroll:read:tenant",
    "payroll:run",
    "payroll:update",
    "crm:create",
    "crm:list",
    "crm:read",
    "crm:update",
    "crm:delete",
    "documents:create",
    "documents:list",
    "documents:read",
    "documents:update",
    "documents:delete",
    "ai:ask",
    "ai:assist:tenant",
    "ai:generate:project_report",
    "ai:generate:financial_report",
    "analytics:read:tenant_kpis",
  ],
  PROJECT_MANAGER: [
    "estimate:create",
    "estimate:list:own",
    "estimate:read:own",
    "estimate:update:own",
    "estimate:send:own",
    "invoice:create",
    "invoice:list:own",
    "invoice:read:own",
    "invoice:update:own",
    "invoice:send:own",
    "project:create:own",
    "project:list:own",
    "project:read:own",
    "project:update:own",
    "project:assign:worker",
    "project:assign:driver",
    "project:assign:task",
    "project:read:team",
    "project:read:schedule",
    "task:create:project",
    "task:list:project",
    "task:read:project",
    "task:update:project",
    "task:assign:worker",
    "task:assign:driver",
    "expenses:list:project",
    "expenses:read:project",
    "time:create:own_entry",
    "time:read:own",
    "payroll:read:own",
    "scheduling:read:own",
    "documents:list:project",
    "documents:read:project",
    "documents:upload:project",
    "documents:comment:project",
    "ai:ask",
    "ai:assist:project",
    "ai:generate:project_report",
  ],
  WORKER: [
    "project:list:assigned",
    "project:read:assigned",
    "task:list:assigned",
    "task:read:assigned",
    "task:update:own",
    "expenses:create:own",
    "expenses:list:own",
    "expenses:read:own",
    "time:create:own_entry",
    "time:read:own",
    "scheduling:read:own",
    "documents:list:assigned",
    "documents:read:assigned",
    "documents:upload:assigned",
    "ai:ask",
    "ai:assist:task",
  ],
  DRIVER: [
    "project:list:delivery_assigned",
    "project:read:delivery_info",
    "task:list:delivery",
    "task:read:delivery",
    "task:update:delivery",
    "inventory:read:delivery_items",
    "expenses:create:delivery",
    "expenses:list:own",
    "expenses:read:own",
    "time:create:own_entry",
    "time:read:own",
    "scheduling:read:own",
    "documents:upload:delivery",
    "documents:read:delivery",
    "ai:ask",
    "ai:assist:delivery",
  ],
  VIEWER: [
    "estimate:read",
    "estimate:list",
    "invoice:read",
    "invoice:list",
    "project:read",
    "project:list",
    "crm:read",
    "crm:list",
    "inventory:read",
    "inventory:list",
    "expenses:read",
    "expenses:list",
    "scheduling:read",
    "time:read",
    "payroll:read",
    "documents:read",
    "documents:list",
    "ai:ask",
    "ai:generate:demo_report",
  ],
} as const;

// ============================================================================
// CRITICAL PERMISSIONS - Not Granted by Default to PM
// ============================================================================

/**
 * These permissions exist in the catalog but are NOT granted to PROJECT_MANAGER
 * by default. They require TenantSettings flags to enable.
 */
export const CRITICAL_PM_PERMISSIONS = {
  APPROVALS: [
    "estimate:approve",
    "invoice:approve",
    "changeorder:approve",
  ],
  
  DELETES: [
    "estimate:delete:own",
    "invoice:delete:own",
    "changeorder:delete:own",
  ],
  
  FINANCIAL_VISIBILITY: [
    "project:read:financial",
    "estimate:read:profit",
    "invoice:read:profit",
    "analytics:read:tenant_kpis",
  ],
} as const;

// ============================================================================
// TENANT SETTINGS FLAGS - PM Gating Flags
// ============================================================================

/**
 * TenantSettings boolean flags that control critical PM permissions
 */
export interface PMGatingFlags {
  pmCanApproveEstimates: boolean;
  pmCanApproveInvoices: boolean;
  pmCanApproveChangeOrders: boolean;
  pmCanSeeProjectFinancials: boolean;
  pmCanDeleteOwnEstimates: boolean;
  pmCanDeleteOwnInvoices: boolean;
  pmCanDeleteOwnChangeOrders: boolean;
}

// ============================================================================
// HELPER FUNCTIONS
// ============================================================================

/**
 * Check if a role has higher or equal authority than another role
 */
export function hasHigherOrEqualAuthority(
  role1: RoleCode,
  role2: RoleCode
): boolean {
  return ROLE_HIERARCHY[role1] <= ROLE_HIERARCHY[role2];
}

/**
 * Get all permissions for a role (baseline grants only)
 */
export function getRolePermissions(role: RoleCode): readonly Permission[] {
  return ROLE_PERMISSIONS[role] || [];
}

/**
 * Check if a role has a specific permission (baseline check only)
 */
export function roleHasPermission(
  role: RoleCode,
  permission: Permission
): boolean {
  return ROLE_PERMISSIONS[role]?.includes(permission) ?? false;
}

/**
 * Get role metadata
 */
export function getRoleMetadata(role: RoleCode): RoleMetadata {
  return ROLE_METADATA[role];
}

// ============================================================================
// VALIDATION STATISTICS
// ============================================================================

export const RBAC_STATS = {
  totalRoles: 5,
  totalPermissions: 140,
  criticalPermissions: 10,
  permissionsPerRole: {
    ADMIN: 79,
    PROJECT_MANAGER: 38,
    WORKER: 16,
    DRIVER: 16,
    VIEWER: 19,
  },
  phase: "PHASE_1_INTERNAL_MEMBERS",
  generatedAt: "2025-11-18T21:20:30.339Z",
} as const;
