/**
 * 🌱 RBAC Seed Data - AUTO-GENERATED
 * 
 * Generated: 2025-11-18T21:20:30.352Z
 * Phase: Phase 1 - Internal Members Only
 * Source: rbac_schema_v9.0.yml
 * Generator: rbac-generator-v9.0.ts
 * 
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * Regenerate using: npx tsx rbac-generator-v9.0.ts
 * 
 * This seed file creates:
 * 1. All permissions from the catalog
 * 2. All Phase 1 roles (5 internal roles)
 * 3. Role-Permission grants (baseline only)
 * 
 * Note: Critical PM permissions are cataloged but NOT granted by default
 */

import { PrismaClient } from "@prisma/client";
import { v7 as uuidv7 } from "uuid";

const prisma = new PrismaClient();

// ============================================================================
// PERMISSION CATALOG - All Permissions
// ============================================================================

const PERMISSIONS = [
  "accesscontrol:manage:service_accounts",
  "accesscontrol:read",
  "accesscontrol:update:tenant_roles",
  "ai:ask",
  "ai:assist:delivery",
  "ai:assist:project",
  "ai:assist:task",
  "ai:assist:tenant",
  "ai:generate:demo_report",
  "ai:generate:financial_report",
  "ai:generate:project_report",
  "analytics:read:tenant_kpis",
  "changeorder:approve",
  "changeorder:delete:own",
  "crm:create",
  "crm:delete",
  "crm:list",
  "crm:read",
  "crm:update",
  "documents:comment:project",
  "documents:create",
  "documents:delete",
  "documents:list",
  "documents:list:assigned",
  "documents:list:project",
  "documents:read",
  "documents:read:assigned",
  "documents:read:delivery",
  "documents:read:project",
  "documents:update",
  "documents:upload:assigned",
  "documents:upload:delivery",
  "documents:upload:project",
  "estimate:approve",
  "estimate:create",
  "estimate:delete",
  "estimate:delete:own",
  "estimate:list",
  "estimate:list:own",
  "estimate:read",
  "estimate:read:own",
  "estimate:read:profit",
  "estimate:send",
  "estimate:send:own",
  "estimate:update",
  "estimate:update:own",
  "expenses:approve",
  "expenses:create",
  "expenses:create:delivery",
  "expenses:create:own",
  "expenses:delete",
  "expenses:list",
  "expenses:list:own",
  "expenses:list:project",
  "expenses:read",
  "expenses:read:own",
  "expenses:read:project",
  "expenses:update",
  "identity:invite:user",
  "identity:read:tenant_users",
  "identity:update:tenant_users",
  "inventory:adjust:quantity",
  "inventory:create:item",
  "inventory:investigate:loss",
  "inventory:list",
  "inventory:read",
  "inventory:read:delivery_items",
  "inventory:update:item",
  "invoice:approve",
  "invoice:create",
  "invoice:delete",
  "invoice:delete:own",
  "invoice:list",
  "invoice:list:own",
  "invoice:read",
  "invoice:read:own",
  "invoice:read:profit",
  "invoice:send",
  "invoice:send:own",
  "invoice:update",
  "invoice:update:own",
  "invoice:writeoff",
  "membership:manage:roles",
  "membership:read:tenant_members",
  "membership:update:tenant_members",
  "payroll:read",
  "payroll:read:own",
  "payroll:read:tenant",
  "payroll:run",
  "payroll:update",
  "project:assign:driver",
  "project:assign:pm",
  "project:assign:task",
  "project:assign:worker",
  "project:create",
  "project:create:own",
  "project:delete",
  "project:list",
  "project:list:assigned",
  "project:list:delivery_assigned",
  "project:list:own",
  "project:read",
  "project:read:assigned",
  "project:read:delivery_info",
  "project:read:financial",
  "project:read:own",
  "project:read:schedule",
  "project:read:team",
  "project:update",
  "project:update:own",
  "scheduling:create",
  "scheduling:read",
  "scheduling:read:own",
  "scheduling:update",
  "task:assign:driver",
  "task:assign:worker",
  "task:create",
  "task:create:project",
  "task:delete",
  "task:list",
  "task:list:assigned",
  "task:list:delivery",
  "task:list:project",
  "task:read",
  "task:read:assigned",
  "task:read:delivery",
  "task:read:project",
  "task:update",
  "task:update:delivery",
  "task:update:own",
  "task:update:project",
  "tenant:manage:features",
  "tenant:manage:modules",
  "tenant:read",
  "tenant:update",
  "time:correct:tenant",
  "time:create:own_entry",
  "time:read",
  "time:read:own",
  "time:read:tenant",
];

// ============================================================================
// ROLES - Phase 1 Internal Members
// ============================================================================

const ROLES = [
  {
    code: "ADMIN",
    hierarchy: 0,
    displayName: "Administrator",
    description: "Tenant owner with full control of business data and tenant configuration within their tenant",
    roleType: "INTERNAL",
  },
  {
    code: "PROJECT_MANAGER",
    hierarchy: 2,
    displayName: "Project Manager",
    description: "Scoped manager responsible for own/assigned projects, estimates, invoices, and teams",
    roleType: "INTERNAL",
  },
  {
    code: "WORKER",
    hierarchy: 8,
    displayName: "Field Worker",
    description: "Field or office execution role working on assigned projects and tasks",
    roleType: "INTERNAL",
  },
  {
    code: "DRIVER",
    hierarchy: 9,
    displayName: "Driver",
    description: "Delivery and logistics role with minimal access to delivery-related information",
    roleType: "INTERNAL",
  },
  {
    code: "VIEWER",
    hierarchy: 10,
    displayName: "Viewer",
    description: "Read-only role for demos and learning in sandbox tenants only",
    roleType: "INTERNAL",
  },
];

// ============================================================================
// ROLE PERMISSIONS - Baseline Grants
// ============================================================================

const ROLE_PERMISSIONS: Record<string, string[]> = {
  ADMIN: [
    "tenant:read",
    "tenant:update",
    "tenant:manage:modules",
    "tenant:manage:features",
    "identity:invite:user",
    "identity:read:tenant_users",
    "identity:update:tenant_users",
    "membership:manage:roles",
    "membership:read:tenant_members",
    "membership:update:tenant_members",
    "accesscontrol:read",
    "accesscontrol:update:tenant_roles",
    "accesscontrol:manage:service_accounts",
    "estimate:create",
    "estimate:list",
    "estimate:read",
    "estimate:update",
    "estimate:delete",
    "estimate:send",
    "estimate:approve",
    "invoice:create",
    "invoice:list",
    "invoice:read",
    "invoice:update",
    "invoice:delete",
    "invoice:send",
    "invoice:approve",
    "invoice:writeoff",
    "project:create",
    "project:list",
    "project:read",
    "project:update",
    "project:delete",
    "project:assign:pm",
    "project:assign:worker",
    "project:assign:driver",
    "project:read:financial",
    "task:create",
    "task:list",
    "task:read",
    "task:update",
    "task:delete",
    "task:assign:worker",
    "task:assign:driver",
    "expenses:create",
    "expenses:list",
    "expenses:read",
    "expenses:update",
    "expenses:delete",
    "expenses:approve",
    "inventory:create:item",
    "inventory:list",
    "inventory:read",
    "inventory:update:item",
    "inventory:adjust:quantity",
    "inventory:investigate:loss",
    "scheduling:create",
    "scheduling:read",
    "scheduling:update",
    "time:read:tenant",
    "time:correct:tenant",
    "payroll:read:tenant",
    "payroll:run",
    "payroll:update",
    "crm:create",
    "crm:list",
    "crm:read",
    "crm:update",
    "crm:delete",
    "documents:create",
    "documents:list",
    "documents:read",
    "documents:update",
    "documents:delete",
    "ai:ask",
    "ai:assist:tenant",
    "ai:generate:project_report",
    "ai:generate:financial_report",
    "analytics:read:tenant_kpis",
  ],
  PROJECT_MANAGER: [
    "estimate:create",
    "estimate:list:own",
    "estimate:read:own",
    "estimate:update:own",
    "estimate:send:own",
    "invoice:create",
    "invoice:list:own",
    "invoice:read:own",
    "invoice:update:own",
    "invoice:send:own",
    "project:create:own",
    "project:list:own",
    "project:read:own",
    "project:update:own",
    "project:assign:worker",
    "project:assign:driver",
    "project:assign:task",
    "project:read:team",
    "project:read:schedule",
    "task:create:project",
    "task:list:project",
    "task:read:project",
    "task:update:project",
    "task:assign:worker",
    "task:assign:driver",
    "expenses:list:project",
    "expenses:read:project",
    "time:create:own_entry",
    "time:read:own",
    "payroll:read:own",
    "scheduling:read:own",
    "documents:list:project",
    "documents:read:project",
    "documents:upload:project",
    "documents:comment:project",
    "ai:ask",
    "ai:assist:project",
    "ai:generate:project_report",
  ],
  WORKER: [
    "project:list:assigned",
    "project:read:assigned",
    "task:list:assigned",
    "task:read:assigned",
    "task:update:own",
    "expenses:create:own",
    "expenses:list:own",
    "expenses:read:own",
    "time:create:own_entry",
    "time:read:own",
    "scheduling:read:own",
    "documents:list:assigned",
    "documents:read:assigned",
    "documents:upload:assigned",
    "ai:ask",
    "ai:assist:task",
  ],
  DRIVER: [
    "project:list:delivery_assigned",
    "project:read:delivery_info",
    "task:list:delivery",
    "task:read:delivery",
    "task:update:delivery",
    "inventory:read:delivery_items",
    "expenses:create:delivery",
    "expenses:list:own",
    "expenses:read:own",
    "time:create:own_entry",
    "time:read:own",
    "scheduling:read:own",
    "documents:upload:delivery",
    "documents:read:delivery",
    "ai:ask",
    "ai:assist:delivery",
  ],
  VIEWER: [
    "estimate:read",
    "estimate:list",
    "invoice:read",
    "invoice:list",
    "project:read",
    "project:list",
    "crm:read",
    "crm:list",
    "inventory:read",
    "inventory:list",
    "expenses:read",
    "expenses:list",
    "scheduling:read",
    "time:read",
    "payroll:read",
    "documents:read",
    "documents:list",
    "ai:ask",
    "ai:generate:demo_report",
  ],
};

// ============================================================================
// SEED EXECUTION
// ============================================================================

async function seedRBAC() {
  console.log("🌱 Starting RBAC seed...");

  try {
    // Step 1: Create all permissions
    console.log("\n📝 Creating permissions...");
    let permissionCount = 0;

    for (const permissionCode of PERMISSIONS) {
      await prisma.permission.upsert({
        where: { permissionCode },
        update: {},
        create: {
          id: uuidv7(),
          permissionCode,
          description: `Permission for ${permissionCode}`,
          isActive: true,
        },
      });
      permissionCount++;
    }

    console.log(`✅ Created/verified ${permissionCount} permissions`);

    // Step 2: Create all roles
    console.log("\n👥 Creating roles...");
    let roleCount = 0;

    for (const role of ROLES) {
      await prisma.role.upsert({
        where: { roleCode: role.code },
        update: {
          hierarchy: role.hierarchy,
          displayName: role.displayName,
          description: role.description,
          roleType: role.roleType,
        },
        create: {
          id: uuidv7(),
          roleCode: role.code,
          hierarchy: role.hierarchy,
          displayName: role.displayName,
          description: role.description,
          roleType: role.roleType,
          isActive: true,
        },
      });
      roleCount++;
    }

    console.log(`✅ Created/verified ${roleCount} roles`);

    // Step 3: Create role-permission grants
    console.log("\n🔗 Creating role-permission grants...");
    let grantCount = 0;

    for (const [roleCode, permissions] of Object.entries(ROLE_PERMISSIONS)) {
      // Get role
      const role = await prisma.role.findUnique({
        where: { roleCode },
      });

      if (!role) {
        console.error(`❌ Role not found: ${roleCode}`);
        continue;
      }

      // Delete existing grants for this role (idempotent seed)
      await prisma.rolePermission.deleteMany({
        where: { roleId: role.id },
      });

      // Create new grants
      for (const permissionCode of permissions) {
        const permission = await prisma.permission.findUnique({
          where: { permissionCode },
        });

        if (!permission) {
          console.error(`❌ Permission not found: ${permissionCode}`);
          continue;
        }

        await prisma.rolePermission.create({
          data: {
            id: uuidv7(),
            roleId: role.id,
            permissionId: permission.id,
          },
        });
        grantCount++;
      }

      console.log(`  ${roleCode}: ${permissions.length} permissions granted`);
    }

    console.log(`\n✅ Created ${grantCount} role-permission grants`);

    // Summary
    console.log("\n" + "=".repeat(70));
    console.log("📊 RBAC Seed Summary");
    console.log("=".repeat(70));
    console.log(`Permissions: ${permissionCount}`);
    console.log(`Roles: ${roleCount}`);
    console.log(`Role-Permission Grants: ${grantCount}`);
    console.log(`Phase: PHASE_1_INTERNAL_MEMBERS`);
    console.log("=".repeat(70));
    console.log("\n✅ RBAC seed completed successfully!\n");
  } catch (error) {
    console.error("\n❌ RBAC seed failed:", error);
    throw error;
  } finally {
    await prisma.$disconnect();
  }
}

// Execute seed
seedRBAC()
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });
